//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Searching.Shared.API.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class User
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Mail { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string LastName { get; set; }
        [DataMember]
        public string Phone { get; set; }
        [DataMember]
        public string Gender { get; set; }
        [DataMember]
        public DateTime? Date_Bearthday { get; set; }
        [DataMember]
        public string Password { get; set; }
        [DataMember]
        public string Info { get; set; }
        [DataMember]
        public int? CountryId { get; set; }
        [DataMember]
        public byte? TypeLogin { get; set; }
        [DataMember]
        public int? CityId { get; set; }
    }
}
